name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BCX Bridge (React)
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          scripts: |
            mkdir test
            cd test
            git clone https://github.com/mastervectormaster/bcx-bridge-demo.git
            echo 'Bridge Deployment successful on the server'
